name: Build and test Yopta Node.js

on:
    push:
        branches: [master, develop]
    pull_request:
        branches: [master, develop]

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node: ['14', '15', '16']
        name: Node ${{ matrix.node }} sample
        steps:
            - uses: actions/checkout@v2
            - name: Setup node
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node }}
            - run: npm install
            - run: npm run build
            - run: npm test
